### PR TITLE
Initial commit for the agent-tui

### PR DESCRIPTION
**Pull request by celebdor**
This first tool in the repository gives you a terminal user interface that helps in reconfiguring agent based installations that fail some checks.

Signed-off-by: Antoni Segura Puimedon <antoni@redhat.com>

### CODE REVIEW

**Review by rwsu — COMMENTED** [review]
Looks like a good starting point. I was able to build and try it out.

/lgtm

**Comment by celebdor** [comment]
The issue with golangci-lint is https://github.com/golangci/golangci-lint/issues/3289 . I think we'll have to disable it for now. I'll create a ticket for adding a container build of golangci-lint that can deal with C wrapping

**Pull request merged**
