### PR TITLE
OCPBUGS-7731: Fix cancel user prompt

### PR DESCRIPTION
**Pull request by andfasano**
The current patch takes care of cancelling the countdown thread when the timeout dialog gets interrupted due a sudden failing check.
In addition to some refactoring to simplify the code, this patch also brings back the timeout dialog to one-off display (it will be shown only the first time)

### CODE REVIEW

**Comment by zaneb** [comment]
I'm not 100% clear on what the current behaviour is, but it seems to me that to avoid breaking people/automation that don't know about the TUI, only interacting with the TUI should cancel the timer. Otherwise if it succeeds even once we should probably exit within 30s.
If a failure cancelled the timer but we started it again the next time it succeeded, that would be ok too.

**Comment by andfasano** [comment]
> I'm not 100% clear on what the current behaviour is, but it seems to me that to avoid breaking people/automation that don't know about the TUI, only interacting with the TUI should cancel the timer. Otherwise if it succeeds even once we should probably exit within 30s. If a failure cancelled the timer but we started it again the next time it succeeded, that would be ok too.

That's what we have in this patch right now, with the exception that if a failure cancelled the timer then it's up to user to fix the problem and decide when to stop the agent-tui to proceed with the installation

**Pull request merged**
